/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication8.form;

import java.util.function.Consumer;
import javaapplication8.service.SanPhamService;
import javaapplication8.service.SanPhamThuocTinhService;
import javaapplication8.service.serviceimpl.SanPhamServiceImpl;
import javaapplication8.service.serviceimpl.SanPhamThuocTinhServiceImpl;
import javaapplication8.until.CodeGeneratorUtil;
import javaapplication8.until.ValidationUtil;
import javax.swing.JOptionPane;

/**
 *
 * @author dungc
 */
public class ThemNhanhSP extends javax.swing.JFrame {

    private ThemSanPhamChiTiet parentFrame; // Thay JFrame bằng SanPham_Form
    private String selectedTable;
    private final SanPhamService service_sp = new SanPhamServiceImpl();
    // Thêm biến callback để gọi từ HomeView
    private Runnable onCloseCallback;
    private Consumer<String> onTenMoiCallback;

    public ThemNhanhSP(ThemSanPhamChiTiet parent, Runnable onCloseCallback) {
        this.parentFrame = parent;
        this.onCloseCallback = onCloseCallback;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * Creates new form ThemNhanhTT
     */
    public ThemNhanhSP() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public void setOnTenMoiCallback(Consumer<String> callback) {
        this.onTenMoiCallback = callback;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_themnhanh = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_sanphamthemnhanh = new javax.swing.JTextField();
        btn_themnhanh = new javax.swing.JButton();
        lbl_thongbaothemnhanh = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_themnhanh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_themnhanh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_themnhanh.setText("Thêm Nhanh Sản Phẩm");

        jLabel2.setText("Tên sản phẩm");

        btn_themnhanh.setText("Thêm");
        btn_themnhanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themnhanhActionPerformed(evt);
            }
        });

        lbl_thongbaothemnhanh.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_themnhanh)
                .addGap(98, 98, 98))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_sanphamthemnhanh, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                            .addComponent(lbl_thongbaothemnhanh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lbl_themnhanh)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_themnhanh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_sanphamthemnhanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_thongbaothemnhanh, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_themnhanh)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themnhanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themnhanhActionPerformed
        String ma = CodeGeneratorUtil.generateSanPham();

        String ten = txt_sanphamthemnhanh.getText().trim();
        String moTa = "";
        // Kiểm tra tên không được để trống
        if (ValidationUtil.isEmpty(ten)) {
            lbl_thongbaothemnhanh.setText("Tên sản phẩm không được để trống");
            return;
        }

        if (service_sp.kiemTraTenSanPhamDaTonTai(ten)) {
            JOptionPane.showMessageDialog(this, "Tên sản phẩm đã tồn tại!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int luachon = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm sản phẩm không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (luachon == JOptionPane.YES_OPTION) {
            boolean them = service_sp.addSanPham(ma, ten, moTa);
            if (them) {
                JOptionPane.showMessageDialog(this, "Thêm sản phẩm thành công.");
                // Gọi callback nếu đã được truyền vào
                if (onCloseCallback != null) {
                    onCloseCallback.run();  // Gọi phương thức callback
                    onTenMoiCallback.accept(ten); // Gửi tên vừa thêm về
                }
               

                this.dispose();  // Đóng cửa sổ ThemNhanhTT
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại.");
            }
        }


    }//GEN-LAST:event_btn_themnhanhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemNhanhSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemNhanhSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemNhanhSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemNhanhSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemNhanhSP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_themnhanh;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_themnhanh;
    private javax.swing.JLabel lbl_thongbaothemnhanh;
    private javax.swing.JTextField txt_sanphamthemnhanh;
    // End of variables declaration//GEN-END:variables

    void setSelectedTableName(String tableName) {
        this.selectedTable = tableName;
    }

    public String getSelectedTableName() {
        return this.selectedTable;
    }


    }
