/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication8.form;

import java.awt.Frame;
import java.awt.Image;
import java.util.List;
import javaapplication8.model.SanPham_ChiTiet;
import javaapplication8.service.SanPhamChiTietService;
import javaapplication8.service.SanPhamService;
import javaapplication8.service.serviceimpl.SanPhamChiTietServiceImpl;
import javaapplication8.service.serviceimpl.SanPhamServiceImpl;
import javaapplication8.until.CodeGeneratorUtil;
import javaapplication8.until.ValidationUtil;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author dungc
 */
public class ThongTinSanPhamChiTiet extends javax.swing.JFrame {

    /**
     * Creates new form ThemSanPhamChiTiet
     */
    private SanPham_Form parentFrame; // Thay JFrame bằng SanPham_Form
    private Runnable onCloseCallback;
    private final SanPhamChiTietService service_spChiTiet = new SanPhamChiTietServiceImpl();
    private final SanPhamService service_sp = new SanPhamServiceImpl();
    private final String maSPCT;
    private String qrPath;

    public ThongTinSanPhamChiTiet(
            SanPham_Form parent,
            Runnable onCloseCallback,
            String maSPCT,
            String tenSP,
            String mauSac,
            String chatLieu,
            String kichThuoc,
            int soLuong,
            double donGia,
            String qrPath
    ) {
        this.parentFrame = parent;
        this.onCloseCallback = onCloseCallback;
        initComponents();
        setLocationRelativeTo(null);

        // Load dữ liệu từ form cha vào combo box
        loadComboboxFromParent();

        // Gán giá trị đã chọn từ bảng
        cbo_sanpham.setSelectedItem(tenSP);
        cbo_mausac.setSelectedItem(mauSac);
        cbo_chatlieu.setSelectedItem(chatLieu);
        cbo_kichthuoc.setSelectedItem(kichThuoc);

        txt_soluongspct.setText(String.valueOf(soLuong));

        // Hiển thị đơn giá dưới dạng số
        txt_dongiaspct.setText(String.format("%.0f", donGia));

        // Lưu maSPCT vào một biến để sử dụng trong phương thức cập nhật
        this.maSPCT = maSPCT;

        this.qrPath = qrPath; // Lưu qrPath vào biến
        hienThiQR(qrPath);
    }

    public void hienThiQR(String qrPath) {
        try {
            ImageIcon icon = new ImageIcon(qrPath);
            Image img = icon.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH); // hoặc kích thước khác
            lbl_qr.setIcon(new ImageIcon(img));
        } catch (Exception e) {
            lbl_qr.setText("Không thể tải QR");
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbo_sanpham = new javax.swing.JComboBox<>();
        cbo_mausac = new javax.swing.JComboBox<>();
        cbo_chatlieu = new javax.swing.JComboBox<>();
        cbo_kichthuoc = new javax.swing.JComboBox<>();
        txt_soluongspct = new javax.swing.JTextField();
        txt_dongiaspct = new javax.swing.JTextField();
        btn_quaylai = new javax.swing.JButton();
        btn_capnhatspct = new javax.swing.JButton();
        lbl_tbsoluong = new javax.swing.JLabel();
        lbl_tbgia = new javax.swing.JLabel();
        lbl_qr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Thông tin sản phẩm chi tiết");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Tên sản phẩm");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Màu sắc");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Chất liệu");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Kích thước");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Số lượng");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Giá");

        cbo_sanpham.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbo_mausac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbo_chatlieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbo_kichthuoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txt_soluongspct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_soluongspctActionPerformed(evt);
            }
        });

        txt_dongiaspct.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_dongiaspctFocusGained(evt);
            }
        });
        txt_dongiaspct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dongiaspctActionPerformed(evt);
            }
        });

        btn_quaylai.setText("Quay lại");
        btn_quaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quaylaiActionPerformed(evt);
            }
        });

        btn_capnhatspct.setText("Cập nhật");
        btn_capnhatspct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capnhatspctActionPerformed(evt);
            }
        });

        lbl_tbsoluong.setForeground(new java.awt.Color(255, 0, 0));
        lbl_tbsoluong.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lbl_tbsoluongFocusGained(evt);
            }
        });

        lbl_tbgia.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(cbo_mausac, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cbo_sanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(144, 144, 144))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(195, 195, 195)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbo_chatlieu, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(144, 144, 144)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_soluongspct)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbo_kichthuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_dongiaspct, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_tbgia, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                    .addComponent(lbl_tbsoluong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)))
                        .addGap(25, 25, 25)
                        .addComponent(lbl_qr, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btn_quaylai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_capnhatspct)
                .addGap(23, 23, 23))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbo_chatlieu, cbo_kichthuoc, cbo_mausac, cbo_sanpham, txt_dongiaspct, txt_soluongspct});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbo_sanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbo_kichthuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel3)
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbo_mausac, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_dongiaspct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_tbgia, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lbl_qr, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbo_chatlieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_soluongspct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_tbsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_quaylai)
                    .addComponent(btn_capnhatspct))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbo_chatlieu, cbo_kichthuoc, cbo_mausac, cbo_sanpham, txt_dongiaspct, txt_soluongspct});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_capnhatspctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capnhatspctActionPerformed
        // Lấy giá trị từ JComboBox
        String tenSanPham = cbo_sanpham.getSelectedItem().toString();
        String tenMauSac = cbo_mausac.getSelectedItem().toString();
        String tenChatLieu = cbo_chatlieu.getSelectedItem().toString();
        String tenKichThuoc = cbo_kichthuoc.getSelectedItem().toString();

        // Lấy ID từ HashMap (dùng để lấy tên sản phẩm)
        int idSP = parentFrame.getSanPhamDangBanMap().get(tenSanPham);  // ID sản phẩm chung
        int idMauSac = parentFrame.getMauSacMap().get(tenMauSac);
        int idChatLieu = parentFrame.getChatLieuMap().get(tenChatLieu);
        int idKichThuoc = parentFrame.getKichThuocMap().get(tenKichThuoc);

        String donGiaText = txt_dongiaspct.getText().trim();

        // Kiểm tra giá trị Đơn giá
        if (ValidationUtil.isEmpty(donGiaText)) {
            lbl_tbgia.setText("Đơn giá sản phẩm không được để trống");
            return;
        } else if (!ValidationUtil.isNumberic(donGiaText.replace(" VND", "").replace(",", "").trim())) {
            lbl_tbgia.setText("Đơn giá sản phẩm phải là số");
            return;
        } else {
            // Loại bỏ "VND" và chuyển thành double
            donGiaText = donGiaText.replace(" VND", "").replace(",", "").trim();
            double donGia = Double.parseDouble(donGiaText);
            // Kiểm tra giá phải lớn hơn 0
            if (donGia <= 0) {
                lbl_tbgia.setText("Đơn giá sản phẩm phải lớn hơn 0");
                return;
            }
        }

        // Kiểm tra số lượng
        int soLuong;
        if (ValidationUtil.isEmpty(txt_soluongspct.getText().trim())) {
            lbl_tbsoluong.setText("Số lượng sản phẩm không được để trống");
            return;
        } else if (!ValidationUtil.isNumberic(txt_soluongspct.getText().trim())) {
            lbl_tbsoluong.setText("Số lượng sản phẩm phải là số Nguyên");
            return;
        } else if (Integer.parseInt(txt_soluongspct.getText().trim()) <= 0) {
            lbl_tbsoluong.setText("Số lượng sản phẩm phải lớn hơn 0");
            return;
        } else {
            soLuong = Integer.parseInt(txt_soluongspct.getText().trim());
        }

        // Lấy mã sản phẩm chi tiết từ biến đã lưu
        String maSPCT = this.maSPCT;  // Mã sản phẩm chi tiết đã được truyền vào form

        // Xác nhận cập nhật
        int luachon = JOptionPane.showConfirmDialog(this, "Bạn có muốn cập nhật sản phẩm không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (luachon == JOptionPane.YES_OPTION) {
            // Gửi mã sản phẩm chi tiết và các giá trị vào service
            boolean capnhat = service_spChiTiet.updateSanPhamChiTiet(maSPCT, idSP, idMauSac, idChatLieu, idKichThuoc, donGiaText, soLuong);
            if (capnhat) {
                JOptionPane.showMessageDialog(this, "Cập nhật sản phẩm chi tiết thành công.");

                // Cập nhật bảng trong form cha
                parentFrame.capNhatBangSanPhamChiTiet(service_spChiTiet.getAllSanPhamChiTiet());
                parentFrame.macDinhCboSPCT();

                // Gọi callback để form cha cập nhật bảng
                if (onCloseCallback != null) {
                    onCloseCallback.run();
                }

                // Đóng form chi tiết sau khi cập nhật
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại.");
            }
        }
    }//GEN-LAST:event_btn_capnhatspctActionPerformed

    private void txt_dongiaspctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dongiaspctActionPerformed

    }//GEN-LAST:event_txt_dongiaspctActionPerformed

    private void txt_soluongspctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_soluongspctActionPerformed

    }//GEN-LAST:event_txt_soluongspctActionPerformed

    private void btn_quaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quaylaiActionPerformed
        // Gọi callback nếu có để load lại dữ liệu ở form cha
        if (onCloseCallback != null) {
            onCloseCallback.run();
        }
        parentFrame.loadDataSP(); // ← gọi lại phương thức phân trang đúng chuẩn

        // Đóng form hiện tại
        this.dispose();
    }//GEN-LAST:event_btn_quaylaiActionPerformed

    private void txt_dongiaspctFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_dongiaspctFocusGained
        lbl_tbgia.setText("");
    }//GEN-LAST:event_txt_dongiaspctFocusGained

    private void lbl_tbsoluongFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lbl_tbsoluongFocusGained
        lbl_tbsoluong.setText("");
    }//GEN-LAST:event_lbl_tbsoluongFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongTinSanPhamChiTiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongTinSanPhamChiTiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongTinSanPhamChiTiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongTinSanPhamChiTiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongTinSanPhamChiTiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Tạo một instance của SanPham_Form giả để mở form con
                SanPham_Form parent = new SanPham_Form();

                // Tạo và mở form chi tiết
                ThongTinSanPhamChiTiet form = new ThongTinSanPhamChiTiet(
                        parent, // form cha
                        new Runnable() {
                    @Override
                    public void run() {
                        // Callback khi form con đóng, bạn có thể refresh bảng hoặc thực hiện một hành động nào đó
                    }
                },
                        null, "Sản phẩm 1", "Màu đỏ", "Cotton", "M", 50, 100000, null // Các giá trị mẫu
                );
                form.setVisible(true);  // Mở form chi tiết
            }
        });
    }

    private void loadComboboxFromParent() {
        // San phẩm
        cbo_sanpham.removeAllItems();

        for (String ten : parentFrame.getSanPhamDangBanMap().keySet()) {
            cbo_sanpham.addItem(ten);
        }

        // Màu sắc
        cbo_mausac.removeAllItems();
        for (String ten : parentFrame.getMauSacMap().keySet()) {
            cbo_mausac.addItem(ten);
        }

        // Kích thước
        cbo_kichthuoc.removeAllItems();
        for (String ten : parentFrame.getKichThuocMap().keySet()) {
            cbo_kichthuoc.addItem(ten);
        }

        // Chất liệu
        cbo_chatlieu.removeAllItems();
        for (String ten : parentFrame.getChatLieuMap().keySet()) {
            cbo_chatlieu.addItem(ten);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_capnhatspct;
    private javax.swing.JButton btn_quaylai;
    private javax.swing.JComboBox<String> cbo_chatlieu;
    private javax.swing.JComboBox<String> cbo_kichthuoc;
    private javax.swing.JComboBox<String> cbo_mausac;
    private javax.swing.JComboBox<String> cbo_sanpham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbl_qr;
    private javax.swing.JLabel lbl_tbgia;
    private javax.swing.JLabel lbl_tbsoluong;
    private javax.swing.JTextField txt_dongiaspct;
    private javax.swing.JTextField txt_soluongspct;
    // End of variables declaration//GEN-END:variables

    }
